### ISSUE TITLE
can't install remi repo because of GPG key issue on CentOS 8

### ISSUE THREAD

**Issue by Spockie** [inmotionhosting/ansible-role-wordpress#7]
I have amended it in my playbook this way:
```
  pre_tasks:
   - debug:
       msg: I execute before roles

   - name:
     rpm_key:
       state: present
       key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
```

**Comment by Respheal** [comment]
Thanks for the reports! We've resolved this issue with the new version of the php-fpm role released today: https://github.com/inmotionhosting/ansible-role-php_fpm/releases/tag/1.1.0
Please make sure you update any locally-installed roles.
